name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        ruby:
          - 3.0
          - 3.1
          - 3.2
        gemfile:
          - rails-7.0
        allow_failures:
          - false

    runs-on: ${{ matrix.os }}-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake spec || $ALLOW_FAILURES

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # 'bundle install' and cache gems
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: bundle exec rake spec
